export const actionTypes = {
// FETCH STATEMENTS:
    // Login
    FETCH_LOGIN_START: "FETCH_LOGIN_START",
    FETCH_LOGIN_SUCCESS: "FETCH_LOGIN_SUCCESS",
    FETCH_LOGIN_FAIL: "FETCH_LOGIN_FAIL",
    // Projects
    FETCH_PROJECTS_START: "FETCH_PROJECTS_START",
    FETCH_PROJECTS_SUCCESS: "FETCH_PROJECTS_SUCCESS",
    FETCH_PROJECTS_FAIL: "FETCH_PROJECTS_FAIL",
    // Sections
    FETCH_SECTIONS_START: "SET_SECTIONS_START",
    FETCH_SECTIONS_SUCCESS: "FETCH_SECTIONS_SUCCESS",
    FETCH_SECTIONS_FAIL: "FETCH_SECTIONS_FAIL",
    // Markers
    FETCH_MARKERS_START: "FETCH_MARKERS_START",
    FETCH_MARKERS_SUCCESS: "FETCH_MARKERS_SUCCESS",
    FETCH_MARKERS_FAIL: "FETCH_MARKERS_FAIL",
    // Snippets
    FETCH_SNIPPETS_START: "FETCH_SNIPPETS_START",
    FETCH_SNIPPETS_SUCCESS: "FETCH_SNIPPETS_SUCCESS",
    FETCH_SNIPPETS_FAIL: "FETCH_SNIPPETS_FAIL",
// SET STATEMENTS:
    SET_CURRENT_PANEL: "SET_CURRENT_PANEL",
    SET_CURRENT_PROJECT_ID: "SET_CURRENT_PROJECT_ID",
    SET_CURRENT_CODE: "SET_CURRENT_CODE",
    SET_CURRENT_SECTION: "SET_CURRENT_SECTION",
    SET_CURRENT_CODE_ID: "SET_CURRENT_CODE_ID"    
  };